name: muscle_monitoring
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  fl_chart: ^1.1.0
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.5
  flutter_riverpod: ^2.6.1
  get: ^4.7.2
  go_router: ^16.2.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app-icon-2.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
